# Generated by Django 4.2.7 on 2023-11-22 07:38

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimationEpisode',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(help_text='Enter description of the episode', null=True)),
                ('video', models.CharField(help_text='Enter video url', max_length=255, null=True)),
                ('created_date', models.DateField(auto_now=True, null=True, verbose_name='Created date')),
                ('updated_date', models.DateField(auto_now=True, null=True, verbose_name='Updated date')),
                ('episode_number', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Anaimation Episode',
                'verbose_name_plural': 'Animation Episodes',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AnimationSeries',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(help_text='Enter description of the series', null=True)),
                ('created_date', models.DateField(auto_now=True, null=True, verbose_name='Created date')),
                ('updated_date', models.DateField(auto_now=True, null=True, verbose_name='Updated date')),
            ],
            options={
                'verbose_name': 'Animation Series',
                'verbose_name_plural': 'Animation Series(s)',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AnimationSeriesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Animation Series Page',
                'verbose_name_plural': 'Animation Series Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
