# Generated by Django 4.2.7 on 2023-11-02 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animations', '0002_animationepisode_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EpisodeImageOrderable',
        ),
    ]
