# Generated by Django 4.2.6 on 2023-11-01 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='image',
            new_name='author_image',
        ),
    ]
