# Generated by Django 4.2.6 on 2023-11-01 06:58

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('comics', '0002_rename_image_author_author_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicEpisode',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(help_text='Enter description of the episode', null=True)),
                ('created_date', models.DateField(auto_now=True, null=True, verbose_name='Created date')),
                ('updated_date', models.DateField(auto_now=True, null=True, verbose_name='Updated date')),
                ('episode_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Comic Episode',
                'verbose_name_plural': 'Comic Episodes',
            },
            bases=('wagtailcore.page',),
        ),
    ]
