# Generated by Django 4.2.6 on 2023-11-01 09:00

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('comics', '0003_comicepisode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', wagtail.fields.RichTextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComicSeriesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Comic Series Page',
                'verbose_name_plural': 'Comic Series Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ComicSeries',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(help_text='Enter description of the series', null=True)),
                ('created_date', models.DateField(auto_now=True, null=True, verbose_name='Created date')),
                ('updated_date', models.DateField(auto_now=True, null=True, verbose_name='Updated date')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='comics.category')),
                ('series_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Comic Series',
                'verbose_name_plural': 'Comic Series(s)',
            },
            bases=('wagtailcore.page',),
        ),
    ]
