# Generated by Django 4.2.6 on 2023-11-01 09:51

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0004_category_comicseriespage_comicseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicseries',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors', to='comics.author'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Enter description of the category'),
        ),
    ]
