# Generated by Django 4.2.7 on 2023-11-02 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0007_comicepisode_episode_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicseries',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animation_authors', to='comics.author'),
        ),
        migrations.AlterField(
            model_name='comicseries',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animation_categories', to='comics.category'),
        ),
    ]
