# Generated by Django 4.2.7 on 2023-11-22 07:38

import blog.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Blog Listing Page',
                'verbose_name_plural': 'Blog Listing Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('post_summary', models.CharField(blank=True, max_length=250, null=True)),
                ('created_date', models.DateField(auto_now=True, verbose_name='Post Date')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='Updated Date')),
                ('content', wagtail.fields.StreamField([('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True))])), ('blockquote', wagtail.blocks.StructBlock([('quote', wagtail.blocks.TextBlock(required=True))])), ('paragraph', blog.blocks.ParagraphBlock()), ('title', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='add your title', required=True))]))], blank=True, null=True, use_json_field=True)),
            ],
            options={
                'verbose_name': 'Blog Page',
                'verbose_name_plural': 'Blog Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
