# Generated by Django 4.2.7 on 2023-11-02 22:41

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloglistingpage',
            options={'verbose_name': 'Blog Listing Page', 'verbose_name_plural': 'Blog Listing Pages'},
        ),
        migrations.AddField(
            model_name='blogpage',
            name='content',
            field=wagtail.fields.StreamField([('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True))])), ('blockquote', wagtail.blocks.StructBlock([('quote', wagtail.blocks.TextBlock(required=True))])), ('paragraph', wagtail.blocks.StructBlock([('paragraph', wagtail.blocks.RichTextBlock(required=True))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
