# Generated by Django 4.2.7 on 2023-11-03 06:48

import blog.blocks
from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_bloglistingpage_options_blogpage_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpage',
            options={'verbose_name': 'Blog Page', 'verbose_name_plural': 'Blog Pages'},
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='content',
            field=wagtail.fields.StreamField([('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True))])), ('blockquote', wagtail.blocks.StructBlock([('quote', wagtail.blocks.TextBlock(required=True))])), ('paragraph', blog.blocks.ParagraphBlock())], blank=True, null=True, use_json_field=True),
        ),
    ]
