# Generated by Django 4.2.7 on 2023-11-03 06:55

import blog.blocks
from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpage_options_alter_blogpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='content',
            field=wagtail.fields.StreamField([('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True))])), ('blockquote', wagtail.blocks.StructBlock([('quote', wagtail.blocks.TextBlock(required=True))])), ('paragraph', blog.blocks.ParagraphBlock()), ('title', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='add your title', required=True))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
