# Generated by Django 4.2.7 on 2023-11-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
