# Generated by Django 4.2.7 on 2023-11-16 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0002_alter_therapist_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapist',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='therapist',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
