# Generated by Django 4.2.7 on 2023-11-16 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0003_rename_name_therapist_first_name_therapist_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapist',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='last_name',
        ),
    ]
