# Generated by Django 4.2.7 on 2023-11-16 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0004_rename_first_name_therapist_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='profile_photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profile'),
            preserve_default=False,
        ),
    ]
